services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: desweb_postgis_1
    restart: "no"
    env_file:
      - .env
      - .env.dev
    ports:
      - ${DEVELOP_DOCKER_POSTGIS_FORWARDED_PORT}:5432
    volumes: 
      - postgis-data:/var/lib/postgresql/data

    #to ckeck if postgres is already ready. It is used in the depends_on section
    #of the services that use this service
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
    networks:
      - desweb_postgis

  pgadmin4:
    image: dpage/pgadmin4:8.3
    container_name: desweb_pgadmin4_1
    env_file:
      - .env
      - .env.dev
    volumes:
      - ./pgadmin4/data:/var/lib/pgadmin
      - ./pgadmin4/servers/servers.json:/pgadmin4/servers.json
    ports:
      - ${DEVELOP_PGADMIN4_FORWARDED_PORT}:80
    restart: "no"
    networks:
      - desweb_postgis
    depends_on:
      postgis:
        condition: service_healthy

  djdesweb:
    restart: "no"
    container_name: desweb_djangoapi_1
    build: ./djdesweb
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djdesweb:/usr/src/app
    ports:
      - ${DEVELOP_DOCKER_DJANGO_API_FORWARDED_PORT}:8000
    env_file:
      - .env
      - .env.dev
    networks:
      - desweb_postgis

    #to ckeck if postgres is already ready. This service
    #will not start up to the posgis service is ready
    depends_on:
      postgis:
        condition: service_healthy
networks:
   desweb_postgis:
      driver: bridge
#coment
volumes:
  postgis-data:
    driver: local
